<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Concerns\HandlesProfilePicture;
use App\Models\User;
use App\Services\ProfilePictureService;
use Illuminate\Auth\Events\Registered;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rules;
use Illuminate\Validation\ValidationException;
use Illuminate\View\View;

class RegisteredUserController extends Controller
{
    use HandlesProfilePicture;

    public function __construct(
        protected ProfilePictureService $profilePictureService
    ) {
    }

    /**
     * Display the registration view.
     */
    public function create(): View
    {
        $supportedLocales = config('app.supported_locales', ['en']);
        return view('auth.register', compact('supportedLocales'));
    }

    /**
     * Display the register account view (frontend styled).
     */
    public function registerAccount(): View
    {
        $catGifs = $this->profilePictureService->getPicturesByCategory('cats');
        return view('accounts.register', compact('catGifs'));
    }

    /**
     * Handle an incoming registration request.
     *
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request): RedirectResponse
    {
        // Normalize email to lowercase before validation (emails are case-insensitive)
        if ($request->has('email')) {
            $request->merge(['email' => strtolower($request->input('email'))]);
        }

        try {
            $validated = $request->validate([
                'username' => ['required', 'string', 'max:255'],
                'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
                'password' => ['required', 'confirmed', Rules\Password::defaults()],
                'locale' => ['nullable', 'string', 'in:' . implode(',', config('app.supported_locales', ['en']))],
                'cat_gif' => ['nullable', 'string'],
            ], [
                'email.required' => __('messages.email_required'),
                'email.email' => __('messages.email_invalid'),
                'email.unique' => __('messages.email_taken'),
                'username.required' => __('messages.username_required'),
                'password.required' => __('messages.password_required'),
                'password.confirmed' => __('messages.password_confirmation_mismatch'),
            ], [
                'username' => __('common.username'),
                'email' => __('common.email'),
                'password' => __('common.password'),
                'password_confirmation' => __('common.confirm_password'),
            ]);
        } catch (ValidationException $e) {
            // Redirect to register-account page with errors and input
            return redirect()->route('register-account')
                ->withErrors($e->errors())
                ->withInput($request->except('password', 'password_confirmation'));
        }

        // Map profile picture
        $profileData = $this->mapProfilePicture($validated['cat_gif'] ?? null);

        // Create user with 'pending' status (requires admin approval)
        // Slug will be auto-generated by the model observer
        // Email is already normalized to lowercase from validation
        $user = User::create([
            'username' => $validated['username'],
            'email' => $validated['email'],
            'password' => Hash::make($validated['password']),
            'role' => 'user', // All registrations are regular users
            'account_status' => 'pending', // Requires approval
            'locale' => $validated['locale'] ?? config('app.locale', 'en'),
        ] + $profileData);

        event(new Registered($user));

        // Redirect to welcome page with query parameter for modal
        return redirect()->route('welcome', ['registered' => '1'])
            ->with('success', 'Registration submitted successfully! Your account is pending admin approval.');
    }
}
