<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Concerns\HandlesPinToggle;
use App\Http\Controllers\Concerns\HandlesProfilePicture;
use App\Http\Requests\Admin\StoreChildRequest;
use App\Http\Requests\Admin\UpdateChildRequest;
use App\Models\User;
use App\Services\PinService;
use App\Services\ProfilePictureService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;

class ChildrenController extends Controller
{
    use HandlesPinToggle, HandlesProfilePicture;

    public function __construct(
        protected PinService $pinService,
        protected ProfilePictureService $profilePictureService
    ) {
    }

    /**
     * List all children for the current parent user.
     */
    public function index()
    {
        $user = auth()->user();
        $children = $user->children()->orderBy('username')->get();
        
        return view('admin.children.index', compact('children'));
    }

    /**
     * Show the form for creating a new child.
     */
    public function create()
    {
        // Get all profile pictures from profile-pictures/cats folder
        $catGifs = $this->profilePictureService->getPicturesByCategory('cats');
        
        // Generate a PIN to pre-fill the form
        $generatedPin = $this->pinService->generatePin(4);
        
        return view('admin.children.create', compact('catGifs', 'generatedPin'));
    }

    /**
     * Store a newly created child.
     */
    public function store(StoreChildRequest $request)
    {
        $user = auth()->user();
        $validated = $request->validated();
        $usePin = $this->getPinToggleState($request);

        // Generate dummy password for Laravel authentication requirements
        // Email is not required for children (set to NULL)
        // Password won't be used since children access via PIN only
        $dummyPassword = Hash::make(Str::random(32));

        // Map cat_gif to profile_picture with category
        $profileData = $this->mapProfilePicture($validated['cat_gif'] ?? null);
        
        // Slug will be auto-generated by the model observer
        $child = User::create([
            'username' => $validated['username'],
            'email' => null, // Children don't have emails
            'password' => $dummyPassword,
            'role' => 'user',
            'parent_id' => $user->id,
            'is_viewable' => true,
            'account_status' => 'approved',
            'locale' => $user->locale ?? config('app.locale', 'en'),
        ] + $profileData);

        // Handle PIN update
        $this->handlePinUpdate($child, $usePin, $validated['pin'] ?? null);

        return redirect()->route('admin.children.index')
            ->with('success', __('messages.child_created', ['name' => $child->username]));
    }

    /**
     * Show the form for editing a child.
     */
    public function edit(User $child)
    {
        $this->authorize('update', $child);
        
        // Get all profile pictures from profile-pictures/cats folder
        $catGifs = $this->profilePictureService->getPicturesByCategory('cats');
        
        // Get current PIN for display
        $currentPin = $child->getViewPin();
        
        return view('admin.children.edit', compact('child', 'catGifs', 'currentPin'));
    }

    /**
     * Update a child.
     */
    public function update(UpdateChildRequest $request, User $child)
    {
        $user = auth()->user();
        $validated = $request->validated();
        $usePin = $this->getPinToggleState($request);

        // Map cat_gif to profile_picture with category
        $profileData = $this->mapProfilePicture($validated['cat_gif'] ?? null);
        
        // Use database transaction to ensure atomicity of child update and device visibility changes
        \DB::transaction(function () use ($child, $validated, $profileData, $usePin, $user, $request) {
            // Slug will be auto-generated by the model observer if username changes
            $child->update([
                'username' => $validated['username'],
            ] + $profileData);

            // Handle PIN update
            $this->handlePinUpdate($child, $usePin, $validated['pin'] ?? null);

            // Update device visibility for all devices (always process, even if no checkboxes are checked)
            $userDevices = $user->deviceRegistrations()->pluck('id')->toArray();
            
            if (!empty($userDevices)) {
                // Get all checked device IDs from the request
                // Checkboxes send '1' when checked, nothing when unchecked
                $checkedDeviceIds = $request->input('device_visibility', []);
                
                foreach ($userDevices as $deviceId) {
                    // Check if this device is in the checked list
                    // A checkbox sends '1' when checked, or is absent when unchecked
                    $isVisible = isset($checkedDeviceIds[$deviceId]) && ($checkedDeviceIds[$deviceId] == '1' || $checkedDeviceIds[$deviceId] == 1);
                    
                    \App\Models\DeviceChildVisibility::updateOrCreate(
                        [
                            'device_registration_id' => $deviceId,
                            'child_user_id' => $child->id,
                        ],
                        ['is_visible' => $isVisible]
                    );
                }
            }
        });

        return redirect()->route('admin.children.index')
            ->with('success', __('messages.child_updated', ['name' => $child->username]));
    }

    /**
     * Remove a child.
     */
    public function destroy(User $child)
    {
        $this->authorize('delete', $child);
        
        $childName = $child->username;
        $child->delete();

        return redirect()->route('admin.children.index')
            ->with('success', __('messages.child_deleted', ['name' => $childName]));
    }
}
